commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls")), # principal
    path("U/", include("authors.urls")),  # principal

    path('__debug__/', include('debug_toolbar.urls')),
]

store/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from store.views import *

app_name = "store"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("search/", SearchView.as_view(), name="search"),
    path("tag/<slug:slug>", TagView.as_view(), name="tag"),
    path("category/<int:idcategory>/", CategoryView.as_view(), name="category"),
    path("G/<int:pk>/", Goods_View.as_view(), name="goods"),
    path("cart/", Cart_View.as_view(), name='cart'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/models.py
import json
from collections import defaultdict

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.core import serializers
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.urls import reverse
from django.db.models import F, Value
from django.db.models.functions import Concat
from django.utils.translation import gettext_lazy as _  # TRANSLATE as _

from tags.models import TAG
from authors.models import User
from utility.image_utils import resize_img


class E_Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name  # !IMPORTANT ISSO FARA COM QUE NO ADMIN DO DJANGO RETORNE O NOME DO OBJETO

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")


class Manager(models.Manager):
    """ CAN I USE THIS IN A VIEW, IN THIS CASE TESTS IF IS PUBLISHED """

    @staticmethod
    def get_published():
        return E_Commerce.objects.filter(is_available=True).order_by('-id').annotate(
            # GIVE MORE ONE VARIABLE INTO A LIST OF QUERYSET
            author_full_name=Concat(
                F('author__first_name'),
                Value(" "),
                F('author__last_name'),
            )
        ).select_related('author', 'category').prefetch_related(
            'tags')  # THIS IMPROVE READ DATABASE (WORKS ON FOREIGN KEY) # noqa


##################################################################


class E_Composition(models.Model):
    name = models.CharField(max_length=16)
    description = models.TextField(verbose_name=_("Description"), null=True, blank=True)

    def __str__(self):
        return self.name  # !IMPORTANT ISSO FARA COM QUE NO ADMIN DO DJANGO RETORNE O NOME DO OBJETO

    class Meta:
        verbose_name = _("Composition")
        verbose_name_plural = _("Compositions")


class E_Commerce(models.Model):  # ISSO É UMA TABELA NO DJANGO
    objects = Manager()
    title = models.CharField(max_length=40, verbose_name=_("Title"))  # IS LIKE MYSQL VARCHAR(65)
    description = models.TextField(verbose_name=_("Description"))
    slug = models.SlugField(unique=True)
    price = models.FloatField(default=1, verbose_name=_("Price"))
    quantity = models.IntegerField(default=0, verbose_name=_("Quantity"))
    # preparetion_steps = models.TextField(null=True, blank=True)
    # preparetion_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created at"))
    update_at = models.DateTimeField(auto_now=True, verbose_name=_("Update at"))
    is_available = models.BooleanField(default=False, verbose_name=_("Is Available"))

    composition = models.ForeignKey(
        E_Composition, on_delete=models.SET_NULL, null=True, blank=True, default=None, verbose_name=_("Compositions"),
    )
    category = models.ForeignKey(
        E_Category, on_delete=models.SET_NULL, null=True, blank=True, default=None, verbose_name=_("Category"),
    )  # FOREING KEY (CHAVE ESTRANGERIA COM A class Category) on_delete definira o campo como null para não perder os
    # links com demais informações
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, verbose_name=_("Author")
    )
    # GENERIC
    # tags = GenericRelation(
    #     TAG, related_query_name='Remedios'
    # )
    # MANY TO MANY
    tags = models.ManyToManyField(TAG, verbose_name="TAG", blank=True)

    # cover = models.ManyToManyField(Covers, verbose_name="Images")
    # cover = models.ImageField(upload_to='covers/%Y/%m/%d/',
    #                           verbose_name="Cover/Image")  # campo de imagem
    # cover = models.TextField(blank=True, null=True)

    # def get_multiview_images_list(self):
    #     if self.cover:
    #         try:
    #             urls = json.loads(self.cover)
    #             return [url for url in urls]
    #         except json.JSONDecodeError as e:
    #             print("JSON Decode Error:", e)
    #     return []
    #
    # def get_default_image(self):
    #     if self.cover:
    #         try:
    #             urls = json.loads(self.cover)
    #             return [url for url in urls][0]
    #         except (json.JSONDecodeError, IndexError) as e:
    #             print("JSON Decode Error:", e)
    #             return []
    #     return []  # TODO por uma imagem default aqui
    #
    # def set_multiview_images(self, images):
    #     self.multiview_images = json.dumps(images)

    # (blank=True permite campo vazio, default é a imagem padrão caso não exista

    def get_images(self):
        return Covers.objects.filter(e_commerce_obj=self)

    def set_images(self, cover):
        position = 0

        for file in cover:
            position += 1

            # Gera um nome único para cada arquivo
            filename = f"imagem_{self.title}_{self.category}_{self.composition}_{position}"
            # Remove acentuação e caracteres especiais

            Covers(name_img=filename, cover=file, e_commerce_obj=self).save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):  # THIS IS SO IMPORTANT, THIS IS CALLED IN TEMPLATE HTML (HAS THIS IN remedio.html)
        return reverse('store:goods', args=(self.id,))

    class Meta:
        verbose_name = _("Object")
        verbose_name_plural = _("Objects")


class Covers(models.Model):
    name_img = models.CharField(max_length=60)
    cover = models.ImageField(upload_to='covers/%Y/%m/%d/',
                              verbose_name="Cover/Image")  # campo de imagem
    e_commerce_obj = models.ForeignKey(E_Commerce, on_delete=models.CASCADE)

    def __str__(self):
        return self.name_img  # !IMPORTANT ISSO FARA COM QUE NO ADMIN DO DJANGO RETORNE O NOME DO OBJETO

    class Meta:
        verbose_name = _("Cover")
        verbose_name_plural = _("Images")


# Carrinho
class Manage_cart(Manager):
    ...


class E_Cart(models.Model):
    objects = Manage_cart()
    e_commerce = models.ForeignKey(E_Commerce, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    qtde = models.IntegerField()

    # def __str__(self):
    #     return self.id
    class Meta:
        verbose_name = _("Cart")
        verbose_name_plural = _("Requests")

tags/models.py
import string

from django.db import models
from django.utils.text import slugify
from random import SystemRandom


# Create your models here.
class TAG(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    # # HERE WE HAVE THE RELATION GENERIC
    # #  means that will be used in any places, don't link with project..
    # content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)  # CASCADE WILL DELETE THIS LINE IF THE
    # # MAIN OBJ WAS DELETED
    #
    # object_id = models.CharField(max_length=255)  # this will receive id from id_obj that will be using with.
    #
    # content_object = GenericForeignKey("content_type", "object_id")  # Mixing content with TAG

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.name}-'.join(SystemRandom().choices(string.ascii_letters + string.digits, k=5)))
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

store/views.py
import os

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q, Value, F
from django.db.models.functions import Concat
from django.shortcuts import get_list_or_404, Http404, redirect  # object é para um só elemento
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView
from django.utils import translation

from authors.models import Profile
from base_class.view_base import Base_Global_Objects
from store.models import E_Commerce, E_Category, E_Cart
from utility.paginator import make_pagination

from django.utils.translation import gettext_lazy as _  # TRANSLATE as _

# Create your views here.

# constant (means that not be modified, but you can in .env file) it's a var global too.
RANGE_PER_PAGE = int(os.environ.get("RANGE_PER_PAGE", 6))
OBJ_PER_PAGE = int(os.environ.get("OBJ_PER_PAGE", 9))


# THIS MAKES THE SAME THING OF func home {
class ObjectListViewBase(ListView, Base_Global_Objects):
    # This is what I can overwrite
    # allow_empty = True
    # queryset = None
    model = E_Commerce  # DATABASE
    # paginate_by = None
    # paginate_orphans = 0
    context_object_name = 'goods'  # TABLE
    # paginator_class = Paginator
    # page_kwarg = "page"
    ordering = ['-id']  # ORDERBY
    template_name = 'pages/home.html'

    def get_queryset(self, *args, **kwargs):  # RETURN A QUERYSET IN THE ORDER WORDS READ DATABASE
        # AQUI O get_published EM MODELS NÃO CHEGA
        querySet = super(ObjectListViewBase, self).get_queryset()
        querySet = querySet.filter(is_available=True, )  # (FILTER),, send data to web template html
        querySet = querySet.annotate(  # GIVE MORE ONE VARIABLE INTO A LIST OF QUERYSET
            author_full_name=Concat(
                F('author__first_name'),
                Value(" "),
                F('author__last_name'),
            )
        )

        querySetLight = querySet.select_related('author', 'category')  # ! THIS IMPROVE DATABASE READ
        querySetLight = querySetLight.prefetch_related('tags', 'author__profile')  # ! THIS IMPROVES DATABASE READ TOO
        return querySetLight

    def get_context_data(self, *args, **kwargs):
        # cart = self.get_full_cart(request=self.request)  # CARRINHO
        context = super().get_context_data(*args, **kwargs)
        pages = make_pagination(self.request, context.get('goods'), RANGE_PER_PAGE, OBJ_PER_PAGE)
        category = E_Category.objects.filter(e_commerce__isnull=False, e_commerce__is_available=True).distinct()
        language = translation.get_language()
        context.update(
            {'goods': pages['goods_page'],
             'pages': pages,
             'categories': category,
             'language': language,
             'nameSite': self.store_name,
             'current_cart': self.get_full_cart(request=self.request),

             }
        )
        return context  # UPDATE CONTEXT, IN THE OTHER WORDS, CUSTOMIZE WEB TEMPLATE WITH MY PAGINATION FUNC


# } END COMMENT

class HomeView(ObjectListViewBase):
    ...


class CategoryView(ObjectListViewBase):
    template_name = 'pages/category-view.html'

    # def get(self, *args, **kwargs):
    #     raise Http404

    def get_queryset(self, *args, **kwargs):  # RETURN A QUERYSET IN THE ORDER WORDS READ DATABASE
        querySet = super(CategoryView, self).get_queryset()
        querySet = querySet.filter(category__id=self.kwargs.get('idcategory')).order_by(
            '-id')  # (FILTER) send data to web template html
        querySetLight = querySet.select_related('author', 'category').prefetch_related(
            'tags')  # ! THIS IMPROVE DATABASE READ
        get_list_or_404(querySetLight)
        return querySetLight

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryView, self).get_context_data()
        goods = context.get('goods')
        pages = make_pagination(self.request, goods, RANGE_PER_PAGE, OBJ_PER_PAGE)
        context.update(
            {
                'current_cart': self.get_full_cart(request=self.request),

                'goods': pages['goods_page'],
                'pages': pages,
                'categoryTitle': f'{goods[0].category.name}',  # ISSO É PY: F'{ VARIAVEL}' RETORNA STRING
                'is_detail': False,
            }
        )
        return context


class SearchView(ObjectListViewBase):
    template_name = 'pages/search.html'

    def get_queryset(self, *args, **kwargs):
        querySet = super(SearchView, self).get_queryset()
        var_site = self.request.GET.get('q')
        if not var_site:
            raise Http404
        var_site = var_site.strip()  # # '''o | juntamente a função Q faz com que a pesquisa seja OR '''
        querySet = querySet.filter(Q(title__contains=var_site) |
                                   Q(description__contains=var_site) |
                                   Q(category__name__contains=var_site)).order_by('-id')
        querySet = querySet.filter(is_available=True)
        querySetLight = querySet.select_related('author', 'category')  # ! THIS IMPROVE DATABASE READ

        return querySetLight

    def get_context_data(self, *args, **kwargs):
        context = super(SearchView, self).get_context_data()
        var_site = self.request.GET.get('q')
        var_site = var_site.strip()  # # '''o | juntamente a função Q faz com que a pesquisa seja OR '''

        pages = make_pagination(self.request, context.get('goods'), RANGE_PER_PAGE, OBJ_PER_PAGE)
        context.update(
            {
                'current_cart': self.get_full_cart(request=self.request),
                'goods': pages['goods_page'],
                'pages': pages,
                'search_done': var_site,
            }
        )
        return context


class TagView(ObjectListViewBase):
    template_name = 'pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        querySet = super(TagView, self).get_queryset()
        var_site = self.kwargs.get('slug')

        if not var_site:
            raise Http404
        # var_site = var_site.strip()  # # '''o | juntamente a função Q faz com que a pesquisa seja OR '''
        querySet = querySet.filter(tags__slug=var_site).order_by('-id')
        querySet = querySet.filter(is_available=True)
        querySetLight = querySet.select_related('author', 'category')  # ! THIS IMPROVE DATABASE READ

        return querySetLight

    def get_context_data(self, *args, **kwargs):
        context = super(TagView, self).get_context_data()
        # var_site = self.kwargs.get('slug')

        pages = make_pagination(self.request, context.get('goods'), RANGE_PER_PAGE, OBJ_PER_PAGE)
        context.update(
            {
                'current_cart': self.get_full_cart(request=self.request),
                'goods': pages['goods_page'],
                'pages': pages,
                # 'title': var_site
            }
        )
        return context


class Goods_View(DetailView, Base_Global_Objects):
    # DETAIL VIEW WAITS PK

    model = E_Commerce
    context_object_name = 'obj'
    template_name = 'pages/goods-view.html'

    def get_context_data(self, **kwargs):
        context = super(Goods_View, self).get_context_data()

        context.update({
            'current_cart': self.get_full_cart(request=self.request),
            'is_detail': True,
            'nameSite': self.store_name,
        })
        return context


# @method_decorator(login_required(login_url='authors:login', redirect_field_name='next'), name='dispatch')
class Cart_View(TemplateView, Base_Global_Objects):
    template_name = 'pages/cart-view.html'

    def get(self, request, *args, **kwargs):

        current_cart = self.get_full_cart(request=request)

        kwargs.update({'current_cart': current_cart,
                       'nameSite': self.store_name,
                       })
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        if request.POST.get("_method") == 'update':  # DROP DO CARRINHO
            self.update_item_cart(request)
        else:
            id_obj = request.POST.get("id-obj")
            qtd = request.POST.get("qtd")

            self.set_item_cart(request=request, id_obj=id_obj, qtd_bought=qtd)

        return redirect(reverse('store:cart'))

store/templates/pages/cart-view.html
{% extends 'global/base.html' %}
{% load i18n %}

{% block 'title' %}
{{ title }}
{% endblock 'title' %}

{% block 'content' %}
{{current_cart}}
<div class="main-content-container">
    <div class="content-cart-view">
        {% for obj in current_cart %}
            <div class="cart-peace">
                <a class="link-img-cart-view" href={{ obj.e_commerce.get_absolute_url }}>
                <img class="img-cart-view" src={{obj.e_commerce.get_default_image}} alt="">
                <div>
                    <h3 class="title-cart-view">{{obj.e_commerce.title}}</h3>
                    <p class="descripition-cart-view">{{obj.e_commerce.description}}</p>
                </div>
                </a>
                {% comment %} <div class="qtde-select-cart-view">
                    <p>{{obj.qtde}}</p>
                </div> {% endcomment %}

                <form class="remove-all-cart-view" action={% url "store:cart" %} method='post'>
                    {% csrf_token %}


                    <input name="number" type="number" value="{{obj.qtde}}">

                    <input type="hidden" name="_method" value="update">
                    <input type="hidden" value={{obj.e_commerce.pk}} name="id-obj-to-update">
                    <button type='submit' class="update-qtde-cart-view">Update Quantity</button>
                </form>
                <div>
                    <button class='less-qtde-cart-view' onclick="dec(this)">-</button>
                    <button class='add-qtde-cart-view' onclick="inc(this)">+</button>  
                  </div>
            </div>
     

        {% empty %}
            <a href={% url "store:home" %}> <h1>Cart empty add something here </h1></a>
        {% endfor %}
    </div>
</div>
<script>
    function inc(button) {
        let numberInput = button.parentElement.parentElement.querySelector('[name="number"]');
        numberInput.value = parseInt(numberInput.value) + 1;
    }
    
    function dec(button) {
        let numberInput = button.parentElement.parentElement.querySelector('[name="number"]');
        if (parseInt(numberInput.value) > 0) {
            numberInput.value = parseInt(numberInput.value) - 1;
        }
    }
</script>
{% endblock 'content' %}

store/templates/pages/category-view.html
{% extends 'global/base.html' %}
{% load i18n %}

 	{% block 'title' %}
 	{{ categoryTitle }}
 	{% endblock 'title' %}

 	{% block 'content' %}
	<div class="main-content-container">

		{% for obj in goods  %}
			{% include 'partials/card-view.html' %}	
		{% endfor %}
		
	</div>
 	{% endblock 'content' %}

	

store/templates/pages/goods-view.html
{% extends 'global/base.html' %}
{% block 'title' %}
{{ obj.title }}
{% endblock 'title' %}

{% block 'content' %}
<div class="main-content-container">
{% comment %} {{ remedio }} {% endcomment %}
   {% include 'partials/card-view.html' %}
               
</div>
{% endblock 'content' %}

store/templates/pages/home.html
{% extends 'global/base.html' %}
{% load i18n %}
 
 {% comment %} GLOBAL É UMA PASTA NA RAIZ DO APP NO MESMO NIVEL DO PROJETO {% endcomment %}

 	{% block 'title' %}
 	HOME
 	{% endblock 'title' %}

 	{% block 'content' %}
	<div class="main-content-container">
        <div class="merchan">
            <a href="http://" target="_blank" rel="noopener noreferrer"></a>
        </div>
        <div class="content-goods">
        {% for obj in goods  %}
        {% comment %} {{remedio}}<br> {% endcomment %}
        {% include 'partials/card-view.html' %}	
        {% empty %}
            <h1> {% translate "Out of stock" %} </h1>
        {% endfor %}
        </div>
	</div>
 	{% endblock 'content' %}

store/templates/pages/search.html
{% extends 'global/base.html' %}
{% load i18n %}

{% comment %} GLOBAL É UMA PASTA NA RAIZ DO APP NO MESMO NIVEL DO PROJETO {% endcomment %}

	{% block 'title' %}
	Results
	{% endblock 'title' %}

	{% block 'content' %}
   <div class="main-content-container">

	   {% for obj in goods  %}
		   {% include 'partials/card-view.html' %}	
	   {% empty %}
		   <h1>{% translate "No results found about" %} {{ search_done }}😒 </h1>
	   {% endfor %}
	   
   </div>
	{% endblock 'content' %}

store/templates/pages/tag.html
{% extends 'global/base.html' %}
{% comment %} GLOBAL É UMA PASTA NA RAIZ DO APP NO MESMO NIVEL DO PROJETO {% endcomment %}

{% block 'title' %}
	Tags 
{% endblock 'title' %}

{% block 'content' %}
	<div class="main-content-container">

		{% for obj in goods  %}
			{% include 'partials/card-view.html' %}	
		{% endfor %}
		
	</div>
{% endblock 'content' %}